name: 'Coverage Reader'
description: 'Reads the code coverage from the supplied XML string.'
author: 'TeqBench'

# Define your inputs here.
inputs:
  coverage-xml:
    description: 'An XML string with code coverage data. Must conform Cobertura format.'
    required: true

# Define your outputs here.
outputs:
  coverage:
    description: 'The code coverage as a percentage, i.e. 90.5'

runs:
  using: node20
  main: dist/index.js
